# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260930 — do not
# edit by hand. The scheme-full catch-all: requires every group plus the
# engine package at this snapshot's version (docs excluded by design;
# engines ship in texlive-bin).
%define debug_package %{nil}

Name:           texlive-meta
Version:        20260930
Release:        1%{?dist}
Summary:        TeX Live scheme-full, without documentation
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

Requires:       texlive-basic = %{version}
Requires:       texlive-bibtexextra = %{version}
Requires:       texlive-binextra = %{version}
Requires:       texlive-fontsrecommended = %{version}
Requires:       texlive-fontutils = %{version}
Requires:       texlive-formatsextra = %{version}
Requires:       texlive-humanities = %{version}
Requires:       texlive-latex = %{version}
Requires:       texlive-latexextra = %{version}
Requires:       texlive-latexrecommended = %{version}
Requires:       texlive-luatex = %{version}
Requires:       texlive-mathscience = %{version}
Requires:       texlive-metapost = %{version}
Requires:       texlive-pictures = %{version}
Requires:       texlive-plaingeneric = %{version}
Requires:       texlive-pstricks = %{version}
Requires:       texlive-publishers = %{version}
Requires:       texlive-xetex = %{version}
Requires:       texlive-bin = %{version}

%description
Metapackage installing every texlive-* group from tlnet snapshot
20260930 — Arch's texlive-meta shape, minus documentation. TeX engines
ship in texlive-bin from the same snapshot.

%build
cat > README <<'EOF'
texlive-meta — TeX Live scheme-full without documentation.

All texlive-* groups installed by this metapackage are pinned to tlnet
snapshot 20260930. Groups roll biweekly; dnf keeps them on one snapshot
via the version-pinned inter-group Requires.
EOF

%files
%doc README

%changelog
* Wed Sep 30 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260930-1
- metapackage for tlnet snapshot 20260930 (18 groups)
