# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260927 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-humanities
Version:        20260927
Release:        1%{?dist}
Summary:        TeX Live humanities collection — Humanities packages
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/27/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-latex = %{version}

%description
TeX Live humanities collection (Humanities packages) — the texmf-dist data tree
from tlnet snapshot 20260927, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
adtrees
bibleref
bibleref-lds
bibleref-mouth
bibleref-parse
covington
diadia
dramatist
dvgloss
ecltree
edfnotes
edmac
eledform
eledmac
expex
expex-glossonly
gb4e
gb4e-next
gmverse
interlinear
jura
juraabbrev
juramisc
jurarsp
langnames
ledmac
lexikon
lexref
ling-macros
linguex
linguexx
linguistix
liturg
liturgy-cw
metrix
nnext
opbible
parallel
parrun
phonrule
plari
play
poemscol
poetry
poetrytex
qobitree
qtree
reledmac
rrgtrees
rtklage
screenplay
screenplay-pkg
sharedline
sides
stage
textglos
thalie
tree-dvips
verse
xyling
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# upstream scripts carry pre-usrmerge shebangs (#!/bin/python3 and friends);
# the shebang mangler is disabled, so rpm would emit unresolvable file
# dependencies — normalize them to /usr/bin
find staging/texmf-dist -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {} + 2>/dev/null || true
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/bibtex/bst/jurarsp/jurarsp.bst
%{_tl_texmf}/dvips/tree-dvips/tree-dvips91.pro
%{_tl_texmf}/makeindex/juraabbrev/laws.ist
%{_tl_texmf}/scripts/diadia/diadia.lua
%{_tl_texmf}/tex/generic/edmac/edmac.tex
%{_tl_texmf}/tex/generic/edmac/edmacfss.sty
%{_tl_texmf}/tex/generic/edmac/edstanza.tex
%{_tl_texmf}/tex/generic/edmac/tabmac.tex
%{_tl_texmf}/tex/generic/expex/epltxchapno.sty
%{_tl_texmf}/tex/generic/expex/epltxfn.sty
%{_tl_texmf}/tex/generic/expex/eptexfn.tex
%{_tl_texmf}/tex/generic/expex/expex-demo.tex
%{_tl_texmf}/tex/generic/expex/expex.sty
%{_tl_texmf}/tex/generic/expex/expex.tex
%{_tl_texmf}/tex/latex/adtrees/adtrees.sty
%{_tl_texmf}/tex/latex/bibleref-lds/bibleref-lds.sty
%{_tl_texmf}/tex/latex/bibleref-mouth/bibleref-mouth.sty
%{_tl_texmf}/tex/latex/bibleref-parse/bibleref-parse.sty
%{_tl_texmf}/tex/latex/bibleref/bibleref-xidx.sty
%{_tl_texmf}/tex/latex/bibleref/bibleref.sty
%{_tl_texmf}/tex/latex/covington/covington.sty
%{_tl_texmf}/tex/latex/diadia/diadia-english.trsl
%{_tl_texmf}/tex/latex/diadia/diadia-fallback.trsl
%{_tl_texmf}/tex/latex/diadia/diadia-german.trsl
%{_tl_texmf}/tex/latex/diadia/diadia.cfg
%{_tl_texmf}/tex/latex/diadia/diadia.sty
%{_tl_texmf}/tex/latex/dramatist/dramatist.sty
%{_tl_texmf}/tex/latex/dvgloss/dvgloss.sty
%{_tl_texmf}/tex/latex/ecltree/ecltree.sty
%{_tl_texmf}/tex/latex/edfnotes/edfnotes.sty
%{_tl_texmf}/tex/latex/eledform/eledform.sty
%{_tl_texmf}/tex/latex/eledmac/eledmac.sty
%{_tl_texmf}/tex/latex/eledmac/eledpar.sty
%{_tl_texmf}/tex/latex/expex-glossonly/expex-glossonly.sty
%{_tl_texmf}/tex/latex/gb4e-next/gb4e-next.sty
%{_tl_texmf}/tex/latex/gb4e/cgloss4e.sty
%{_tl_texmf}/tex/latex/gb4e/gb4e.sty
%{_tl_texmf}/tex/latex/gmverse/gmverse.sty
%{_tl_texmf}/tex/latex/interlinear/interlinear.sty
%{_tl_texmf}/tex/latex/jura/alphanum.sty
%{_tl_texmf}/tex/latex/jura/jura.cls
%{_tl_texmf}/tex/latex/juraabbrev/juraabbrev.4ht
%{_tl_texmf}/tex/latex/juraabbrev/juraabbrev.sty
%{_tl_texmf}/tex/latex/juramisc/jbgoe.clo
%{_tl_texmf}/tex/latex/juramisc/jbstgallen.clo
%{_tl_texmf}/tex/latex/juramisc/jbtrier.clo
%{_tl_texmf}/tex/latex/juramisc/jurabase.sty
%{_tl_texmf}/tex/latex/juramisc/jurabook.cls
%{_tl_texmf}/tex/latex/juramisc/juraovw.cls
%{_tl_texmf}/tex/latex/juramisc/juraurtl.cls
%{_tl_texmf}/tex/latex/jurarsp/jurarsp.cfg
%{_tl_texmf}/tex/latex/jurarsp/jurarsp.sty
%{_tl_texmf}/tex/latex/langnames/langnames.sty
%{_tl_texmf}/tex/latex/langnames/ln_fams_glot.tex
%{_tl_texmf}/tex/latex/langnames/ln_fams_wals.tex
%{_tl_texmf}/tex/latex/langnames/ln_langs_glot.tex
%{_tl_texmf}/tex/latex/langnames/ln_langs_glot_native.tex
%{_tl_texmf}/tex/latex/langnames/ln_langs_wals.tex
%{_tl_texmf}/tex/latex/langnames/ln_langs_wals_native.tex
%{_tl_texmf}/tex/latex/ledmac/afoot.sty
%{_tl_texmf}/tex/latex/ledmac/ledarab.sty
%{_tl_texmf}/tex/latex/ledmac/ledmac.sty
%{_tl_texmf}/tex/latex/ledmac/ledpar.sty
%{_tl_texmf}/tex/latex/lexikon/lexikon.sty
%{_tl_texmf}/tex/latex/lexref/lexref.sty
%{_tl_texmf}/tex/latex/ling-macros/ling-macros.sty
%{_tl_texmf}/tex/latex/linguex/linguex.sty
%{_tl_texmf}/tex/latex/linguex/linguho.sty
%{_tl_texmf}/tex/latex/linguex/ps-trees.sty
%{_tl_texmf}/tex/latex/linguexx/linguexx.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-american.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-base.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-british.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-english.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-fixpex.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-fonts.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-glossing.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-greek.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-ipa.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-languages.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-leipzig.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-logos.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-malayalam.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-marathi.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-nfss.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix-russian.sty
%{_tl_texmf}/tex/latex/linguistix/linguistix.sty
%{_tl_texmf}/tex/latex/liturg/liturg.sty
%{_tl_texmf}/tex/latex/liturgy-cw/liturgy-cw.sty
%{_tl_texmf}/tex/latex/metrix/metrix.sty
%{_tl_texmf}/tex/latex/nnext/nnext.sty
%{_tl_texmf}/tex/latex/parallel/parallel.sty
%{_tl_texmf}/tex/latex/parrun/parrun.sty
%{_tl_texmf}/tex/latex/phonrule/phonrule.sty
%{_tl_texmf}/tex/latex/plari/plari.cls
%{_tl_texmf}/tex/latex/play/play.cls
%{_tl_texmf}/tex/latex/play/play.sty
%{_tl_texmf}/tex/latex/poemscol/poemscol.sty
%{_tl_texmf}/tex/latex/poetry/poetry.sty
%{_tl_texmf}/tex/latex/poetrytex/poetrytex.sty
%{_tl_texmf}/tex/latex/qobitree/qobitree.tex
%{_tl_texmf}/tex/latex/qtree/qtree.sty
%{_tl_texmf}/tex/latex/reledmac/reledmac.sty
%{_tl_texmf}/tex/latex/reledmac/reledpar.sty
%{_tl_texmf}/tex/latex/rrgtrees/rrgtrees.sty
%{_tl_texmf}/tex/latex/rtklage/rtklage.cls
%{_tl_texmf}/tex/latex/screenplay-pkg/screenplay-pkg.sty
%{_tl_texmf}/tex/latex/screenplay/hardmarg.sty
%{_tl_texmf}/tex/latex/screenplay/screenplay.cls
%{_tl_texmf}/tex/latex/sharedline/sharedline.sty
%{_tl_texmf}/tex/latex/sides/sides.cls
%{_tl_texmf}/tex/latex/stage/stage.cls
%{_tl_texmf}/tex/latex/textglos/textglos.sty
%{_tl_texmf}/tex/latex/thalie/thalie-english.trsl
%{_tl_texmf}/tex/latex/thalie/thalie-fallback.trsl
%{_tl_texmf}/tex/latex/thalie/thalie-french.trsl
%{_tl_texmf}/tex/latex/thalie/thalie-german.trsl
%{_tl_texmf}/tex/latex/thalie/thalie-italian.trsl
%{_tl_texmf}/tex/latex/thalie/thalie.sty
%{_tl_texmf}/tex/latex/tree-dvips/lingmacros.sty
%{_tl_texmf}/tex/latex/tree-dvips/tree-dvips.sty
%{_tl_texmf}/tex/latex/verse/verse.sty
%{_tl_texmf}/tex/latex/xyling/xyling.sty
%{_tl_texmf}/tex/optex/opbible/f-biblon.opm
%{_tl_texmf}/tex/optex/opbible/opbible-hebrew.tex
%{_tl_texmf}/tex/optex/opbible/opbible.opm

%changelog
* Sun Sep 27 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260927-1
- rolled to tlnet snapshot 20260927 (60 members)
