# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260927 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-fontutils
Version:        20260927
Release:        1%{?dist}
Summary:        TeX Live fontutils collection — Graphics and font utilities
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/27/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-basic = %{version}

%description
TeX Live fontutils collection (Graphics and font utilities) — the texmf-dist data tree
from tlnet snapshot 20260927, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
accfonts
afm2pl
albatross
dosepsbin
dvipsconfig
epstopdf
fontinst
fontools
luafindfont
mf2pt1
ps2eps
psutils
ttfutils
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# upstream scripts carry pre-usrmerge shebangs (#!/bin/python3 and friends);
# the shebang mangler is disabled, so rpm would emit unresolvable file
# dependencies — normalize them to /usr/bin
find staging/texmf-dist -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {} + 2>/dev/null || true
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/dvips/dvipsconfig/README
%{_tl_texmf}/dvips/dvipsconfig/addpsctrl
%{_tl_texmf}/dvips/dvipsconfig/config.a3
%{_tl_texmf}/dvips/dvipsconfig/config.a4
%{_tl_texmf}/dvips/dvipsconfig/config.a4grid
%{_tl_texmf}/dvips/dvipsconfig/config.duplong
%{_tl_texmf}/dvips/dvipsconfig/config.dupshort
%{_tl_texmf}/dvips/dvipsconfig/config.envelope
%{_tl_texmf}/dvips/dvipsconfig/config.inv
%{_tl_texmf}/dvips/dvipsconfig/config.manualfeed
%{_tl_texmf}/dvips/dvipsconfig/config.mmgrid
%{_tl_texmf}/dvips/dvipsconfig/config.psgrid
%{_tl_texmf}/dvips/dvipsconfig/config.screen100
%{_tl_texmf}/dvips/dvipsconfig/config.screen100_0
%{_tl_texmf}/dvips/dvipsconfig/config.screen110
%{_tl_texmf}/dvips/dvipsconfig/config.screen120
%{_tl_texmf}/dvips/dvipsconfig/config.screen130
%{_tl_texmf}/dvips/dvipsconfig/config.screen140
%{_tl_texmf}/dvips/dvipsconfig/config.screen150
%{_tl_texmf}/dvips/dvipsconfig/config.screen35
%{_tl_texmf}/dvips/dvipsconfig/config.screen50
%{_tl_texmf}/dvips/dvipsconfig/config.screen70
%{_tl_texmf}/dvips/dvipsconfig/config.screen80
%{_tl_texmf}/dvips/dvipsconfig/config.screen85
%{_tl_texmf}/dvips/dvipsconfig/config.screen90
%{_tl_texmf}/dvips/dvipsconfig/config.simplex
%{_tl_texmf}/dvips/dvipsconfig/config.tek550paper
%{_tl_texmf}/dvips/dvipsconfig/config.tek550transparency
%{_tl_texmf}/dvips/dvipsconfig/config.tray1
%{_tl_texmf}/dvips/dvipsconfig/config.tray2
%{_tl_texmf}/dvips/dvipsconfig/config.tray3
%{_tl_texmf}/dvips/dvipsconfig/config.usledger
%{_tl_texmf}/dvips/dvipsconfig/config.usletter
%{_tl_texmf}/dvips/getafm/getafm.ps
%{_tl_texmf}/fonts/enc/dvips/afm2pl/afm2pl-ot1.enc
%{_tl_texmf}/fonts/enc/dvips/afm2pl/afm2pl-ot1ital.enc
%{_tl_texmf}/fonts/enc/dvips/afm2pl/afm2pl-ot1tt.enc
%{_tl_texmf}/fonts/enc/dvips/afm2pl/afm2pl-texnanlc.enc
%{_tl_texmf}/fonts/enc/dvips/afm2pl/afm2pl-texnanuc.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_cs.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_l7x.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_lgr.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_ly1.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_oml.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_ot1.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_qx.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_t1.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_t2a.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_t2b.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_t2c.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_t3.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_t4.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_t5.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_ts1.enc
%{_tl_texmf}/fonts/enc/dvips/fontools/fontools_ts3.enc
%{_tl_texmf}/fonts/enc/ttf2pk/base/T1-WGL4.enc
%{_tl_texmf}/fonts/lig/afm2pl/accents.lig
%{_tl_texmf}/fonts/lig/afm2pl/bound.lig
%{_tl_texmf}/fonts/lig/afm2pl/default.lig
%{_tl_texmf}/fonts/lig/afm2pl/defpost.lig
%{_tl_texmf}/fonts/lig/afm2pl/defpre.lig
%{_tl_texmf}/fonts/lig/afm2pl/forge.lig
%{_tl_texmf}/fonts/lig/afm2pl/ligtex.lig
%{_tl_texmf}/fonts/sfd/ttf2pk/Big5.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/EUC.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/HKSCS.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/KS-HLaTeX.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/SJIS.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/UBg5plus.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/UBig5.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/UGB.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/UGBK.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/UJIS.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/UKS-HLaTeX.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/UKS.sfd
%{_tl_texmf}/fonts/sfd/ttf2pk/Unicode.sfd
%{_tl_texmf}/metapost/mf2pt1/mf2pt1.mp
%{_tl_texmf}/psutils/paper.cfg
%{_tl_texmf}/scripts/accfonts/mkt1font
%{_tl_texmf}/scripts/accfonts/vpl2ovp
%{_tl_texmf}/scripts/accfonts/vpl2vpl
%{_tl_texmf}/scripts/albatross/albatross.jar
%{_tl_texmf}/scripts/albatross/albatross.sh
%{_tl_texmf}/scripts/dosepsbin/dosepsbin.pl
%{_tl_texmf}/scripts/epstopdf/epstopdf.pl
%{_tl_texmf}/scripts/fontools/afm2afm
%{_tl_texmf}/scripts/fontools/autoinst
%{_tl_texmf}/scripts/fontools/ot2kpx
%{_tl_texmf}/scripts/luafindfont/luafindfont.lua
%{_tl_texmf}/scripts/mf2pt1/mf2pt1.pl
%{_tl_texmf}/scripts/ps2eps/ps2eps.pl
%{_tl_texmf}/scripts/psutils/extractres.pl
%{_tl_texmf}/scripts/psutils/includeres.pl
%{_tl_texmf}/scripts/psutils/psjoin.pl
%{_tl_texmf}/scripts/texlive-extra/fontinst.sh
%{_tl_texmf}/tex/fontinst/afm2pl/README
%{_tl_texmf}/tex/fontinst/afm2pl/ly1.etx
%{_tl_texmf}/tex/fontinst/afm2pl/ly1c.etx
%{_tl_texmf}/tex/fontinst/afm2pl/makesc8y.tex
%{_tl_texmf}/tex/fontinst/base/bbox.sty
%{_tl_texmf}/tex/fontinst/base/cfntinst.sty
%{_tl_texmf}/tex/fontinst/base/finstmsc.sty
%{_tl_texmf}/tex/fontinst/base/fontinst.ini
%{_tl_texmf}/tex/fontinst/base/fontinst.sty
%{_tl_texmf}/tex/fontinst/base/multislot.sty
%{_tl_texmf}/tex/fontinst/base/xfntinst.sty
%{_tl_texmf}/tex/fontinst/latinetx/8r.etx
%{_tl_texmf}/tex/fontinst/latinetx/8y.etx
%{_tl_texmf}/tex/fontinst/latinetx/ot1.etx
%{_tl_texmf}/tex/fontinst/latinetx/ot1c.etx
%{_tl_texmf}/tex/fontinst/latinetx/ot1cj.etx
%{_tl_texmf}/tex/fontinst/latinetx/ot1ctt.etx
%{_tl_texmf}/tex/fontinst/latinetx/ot1i.etx
%{_tl_texmf}/tex/fontinst/latinetx/ot1ij.etx
%{_tl_texmf}/tex/fontinst/latinetx/ot1itt.etx
%{_tl_texmf}/tex/fontinst/latinetx/ot1j.etx
%{_tl_texmf}/tex/fontinst/latinetx/ot1tt.etx
%{_tl_texmf}/tex/fontinst/latinetx/t1.etx
%{_tl_texmf}/tex/fontinst/latinetx/t1c.etx
%{_tl_texmf}/tex/fontinst/latinetx/t1cj.etx
%{_tl_texmf}/tex/fontinst/latinetx/t1i.etx
%{_tl_texmf}/tex/fontinst/latinetx/t1ij.etx
%{_tl_texmf}/tex/fontinst/latinetx/t1j.etx
%{_tl_texmf}/tex/fontinst/latinetx/txtfdmns.etx
%{_tl_texmf}/tex/fontinst/latinmtx/8r.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/8y.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/latin.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/latinsc.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/llbuild.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/lsbuild.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/lsfake.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/lsmisc.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/ltcmds.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/ltpunct.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/lubuild.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/newlatin.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/resetsc.mtx
%{_tl_texmf}/tex/fontinst/latinmtx/unsetalf.mtx
%{_tl_texmf}/tex/fontinst/mathetx/euex.etx
%{_tl_texmf}/tex/fontinst/mathetx/eufrak.etx
%{_tl_texmf}/tex/fontinst/mathetx/eurm.etx
%{_tl_texmf}/tex/fontinst/mathetx/euscr.etx
%{_tl_texmf}/tex/fontinst/mathetx/msam.etx
%{_tl_texmf}/tex/fontinst/mathetx/msbm.etx
%{_tl_texmf}/tex/fontinst/mathetx/oml.etx
%{_tl_texmf}/tex/fontinst/mathetx/oms.etx
%{_tl_texmf}/tex/fontinst/mathetx/omx.etx
%{_tl_texmf}/tex/fontinst/mathetx/rsfs.etx
%{_tl_texmf}/tex/fontinst/mathmtx/mathex.mtx
%{_tl_texmf}/tex/fontinst/mathmtx/mathit.mtx
%{_tl_texmf}/tex/fontinst/mathmtx/mathsy.mtx
%{_tl_texmf}/tex/fontinst/misc/csc2x.tex
%{_tl_texmf}/tex/fontinst/misc/csckrn2x.tex
%{_tl_texmf}/tex/fontinst/misc/glyphbox.mtx
%{_tl_texmf}/tex/fontinst/misc/glyphoff.mtx
%{_tl_texmf}/tex/fontinst/misc/glyphon.mtx
%{_tl_texmf}/tex/fontinst/misc/kernoff.mtx
%{_tl_texmf}/tex/fontinst/misc/kernon.mtx
%{_tl_texmf}/tex/fontinst/misc/osf2x.tex
%{_tl_texmf}/tex/fontinst/smbletx/digit2.etx
%{_tl_texmf}/tex/fontinst/smbletx/ts1.etx
%{_tl_texmf}/tex/fontinst/smbletx/ts1i.etx
%{_tl_texmf}/tex/fontinst/smbletx/ts1ij.etx
%{_tl_texmf}/tex/fontinst/smbletx/ts1j.etx
%{_tl_texmf}/tex/fontinst/smblmtx/resetosf.mtx
%{_tl_texmf}/tex/fontinst/smblmtx/textcomp.mtx
%{_tl_texmf}/tex/fontinst/smblmtx/unsetnum.mtx
%{_tl_texmf}/tex/latex/accfonts/CSX.def
%{_tl_texmf}/tex/latex/accfonts/ISO-Latin1.def
%{_tl_texmf}/tex/latex/accfonts/ISO-Latin2.def
%{_tl_texmf}/tex/latex/accfonts/IndUni_Omega.def
%{_tl_texmf}/tex/latex/accfonts/Norman.def
%{_tl_texmf}/tex/latex/fontinst/fontdoc.sty
%{_tl_texmf}/ttf2pk/VPS.rpl
%{_tl_texmf}/ttf2pk/ttf2pk.cfg

%changelog
* Sun Sep 27 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260927-1
- rolled to tlnet snapshot 20260927 (13 members)
