# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260927 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-xetex
Version:        20260927
Release:        1%{?dist}
Summary:        TeX Live xetex collection — XeTeX and packages
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/27/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-basic = %{version}

%description
TeX Live xetex collection (XeTeX and packages) — the texmf-dist data tree
from tlnet snapshot 20260927, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
arabxetex
bidi-atbegshi
bidicontour
bidipagegrid
bidipresentation
bidishadowtext
businesscard-qrcode
cqubeamer
ctex
fixlatvian
font-change-xetex
fontbook
fontwrap
interchar
na-position
philokalia
ptext
shtthesis
simple-resume-cv
simple-thesis-dissertation
tetragonos
ucharclasses
unicode-bidi
unimath-plain-xetex
unisugar
xebaposter
xechangebar
xecjk
xecolor
xecyr
xeindex
xesearch
xespotcolor
xetex
xetex-devanagari
xetex-itrans
xetex-pstricks
xetex-tibetan
xetexconfig
xetexfontinfo
xetexko
xevlna
zbmath-review-template
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# upstream scripts carry pre-usrmerge shebangs (#!/bin/python3 and friends);
# the shebang mangler is disabled, so rpm would emit unresolvable file
# dependencies — normalize them to /usr/bin
find staging/texmf-dist -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {} + 2>/dev/null || true
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabicdigits.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabicdigits.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-farsi-fullvoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-farsi-fullvoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-farsi-novoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-farsi-novoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-farsi-trans-loc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-farsi-trans-loc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-farsi-voc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-farsi-voc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-fullvoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-fullvoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-kashmiri-fullvoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-kashmiri-fullvoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-kashmiri-novoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-kashmiri-novoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-kashmiri-voc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-kashmiri-voc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-kurdish.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-kurdish.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-maghribi-fullvoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-maghribi-fullvoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-maghribi-novoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-maghribi-novoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-maghribi-voc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-maghribi-voc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-malay-fullvoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-malay-fullvoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-malay-novoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-malay-novoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-malay-voc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-malay-voc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-novoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-novoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-pashto-fullvoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-pashto-fullvoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-pashto-novoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-pashto-novoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-pashto-trans-loc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-pashto-trans-loc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-pashto-voc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-pashto-voc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-sindhi-fullvoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-sindhi-fullvoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-sindhi-novoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-sindhi-novoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-sindhi-trans-loc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-sindhi-trans-loc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-sindhi-voc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-sindhi-voc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-trans-dmg.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-trans-dmg.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-trans-loc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-trans-loc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-turk-fullvoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-turk-fullvoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-turk-novoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-turk-novoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-turk-voc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-turk-voc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-uighur.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-uighur.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-urdu-fullvoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-urdu-fullvoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-urdu-novoc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-urdu-novoc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-urdu-trans-loc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-urdu-trans-loc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-urdu-voc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-urdu-voc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-voc.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/arabtex-voc.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/farsidigits.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/farsidigits.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/fixlamalif.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/fixlamalif.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/mirrorpunct.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/arabxetex/mirrorpunct.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/base/qx-unicode.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/base/qx-unicode.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/base/tex-text.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/base/tex-text.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-bb.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-bb.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-bbit.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-bbit.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-bf.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-bf.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-bfit.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-bfit.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-frak.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-frak.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-frakbf.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-frakbf.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-it.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-it.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-scr.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-scr.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-scrbf.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-scrbf.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-sf.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-sf.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-sfbf.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-sfbf.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-sfbfit.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-sfbfit.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-sfit.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-sfit.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-tt.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/unimath-plain-xetex/unimath-tt.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xecjk/full-stop.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xecjk/full-stop.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xecjk/fullwidth-stop.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xecjk/fullwidth-stop.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xecjk/han-simp.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xecjk/han-simp.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xecjk/han-trad.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xecjk/han-trad.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/README
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/devanagarinumerals.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/devanagarinumerals.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/harvardkyoto.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/harvardkyoto.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/iast.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/iast.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/velthuis-sanskrit.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/velthuis-sanskrit.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/velthuis.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-devanagari/velthuis.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/brh-kan.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/brh-kan.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-dvn.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-dvn.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-iast.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-iast.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-kan.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-kan.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-sankan.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-sankan.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-santel.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-santel.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-sdvn.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-sdvn.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-tamil.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-tamil.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-tel.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-itrans/itrans-tel.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-tibetan/loctib.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-tibetan/loctib.tec
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-tibetan/wylie.map
%{_tl_texmf}/fonts/misc/xetex/fontmapping/xetex-tibetan/wylie.tec
%{_tl_texmf}/fonts/opentype/public/philokalia/Philokalia-Regular.otf
%{_tl_texmf}/makeindex/fixlatvian/lv.ist
%{_tl_texmf}/scripts/texlive-extra/xelatex-unsafe.sh
%{_tl_texmf}/scripts/texlive-extra/xetex-unsafe.sh
%{_tl_texmf}/tex/generic/ctex/ctex-spa-macro.tex
%{_tl_texmf}/tex/generic/ctex/ctex-spa-make.tex
%{_tl_texmf}/tex/generic/ctex/ctxdocstrip.tex
%{_tl_texmf}/tex/generic/ctex/zhmap/ctex-zhmap-adobe.tex
%{_tl_texmf}/tex/generic/ctex/zhmap/ctex-zhmap-fandol.tex
%{_tl_texmf}/tex/generic/ctex/zhmap/ctex-zhmap-founder.tex
%{_tl_texmf}/tex/generic/ctex/zhmap/ctex-zhmap-hanyi.tex
%{_tl_texmf}/tex/generic/ctex/zhmap/ctex-zhmap-mac.tex
%{_tl_texmf}/tex/generic/ctex/zhmap/ctex-zhmap-ubuntu.tex
%{_tl_texmf}/tex/generic/ctex/zhmap/ctex-zhmap-windows.tex
%{_tl_texmf}/tex/latex/ctex/config/ctex-name-gbk.cfg
%{_tl_texmf}/tex/latex/ctex/config/ctex-name-utf8.cfg
%{_tl_texmf}/tex/latex/ctex/config/ctex.cfg
%{_tl_texmf}/tex/latex/ctex/config/ctexbackend.cfg
%{_tl_texmf}/tex/latex/ctex/config/ctexopts.cfg
%{_tl_texmf}/tex/latex/ctex/ctex-c5size.clo
%{_tl_texmf}/tex/latex/ctex/ctex-cs4size.clo
%{_tl_texmf}/tex/latex/ctex/ctex.sty
%{_tl_texmf}/tex/latex/ctex/ctexart.cls
%{_tl_texmf}/tex/latex/ctex/ctexbeamer.cls
%{_tl_texmf}/tex/latex/ctex/ctexbook.cls
%{_tl_texmf}/tex/latex/ctex/ctexcap.sty
%{_tl_texmf}/tex/latex/ctex/ctexheading.sty
%{_tl_texmf}/tex/latex/ctex/ctexhook.sty
%{_tl_texmf}/tex/latex/ctex/ctexpatch.sty
%{_tl_texmf}/tex/latex/ctex/ctexrep.cls
%{_tl_texmf}/tex/latex/ctex/ctexsize.sty
%{_tl_texmf}/tex/latex/ctex/ctexspa.def
%{_tl_texmf}/tex/latex/ctex/ctxdoc.cls
%{_tl_texmf}/tex/latex/ctex/dictionary/translator-theorem-dictionary-ChineseGBK.dict
%{_tl_texmf}/tex/latex/ctex/dictionary/translator-theorem-dictionary-ChineseUTF8.dict
%{_tl_texmf}/tex/latex/ctex/engine/ctex-engine-aptex.def
%{_tl_texmf}/tex/latex/ctex/engine/ctex-engine-luatex.def
%{_tl_texmf}/tex/latex/ctex/engine/ctex-engine-pdftex.def
%{_tl_texmf}/tex/latex/ctex/engine/ctex-engine-uptex.def
%{_tl_texmf}/tex/latex/ctex/engine/ctex-engine-xetex.def
%{_tl_texmf}/tex/latex/ctex/fd/c19rm.fd
%{_tl_texmf}/tex/latex/ctex/fd/c19sf.fd
%{_tl_texmf}/tex/latex/ctex/fd/c19tt.fd
%{_tl_texmf}/tex/latex/ctex/fd/c70rm.fd
%{_tl_texmf}/tex/latex/ctex/fd/c70sf.fd
%{_tl_texmf}/tex/latex/ctex/fd/c70tt.fd
%{_tl_texmf}/tex/latex/ctex/fd/jt2zhrm.fd
%{_tl_texmf}/tex/latex/ctex/fd/jt2zhsf.fd
%{_tl_texmf}/tex/latex/ctex/fd/jt2zhtt.fd
%{_tl_texmf}/tex/latex/ctex/fd/jy2zhrm.fd
%{_tl_texmf}/tex/latex/ctex/fd/jy2zhsf.fd
%{_tl_texmf}/tex/latex/ctex/fd/jy2zhtt.fd
%{_tl_texmf}/tex/latex/ctex/fontset/ctex-fontset-adobe.def
%{_tl_texmf}/tex/latex/ctex/fontset/ctex-fontset-fandol.def
%{_tl_texmf}/tex/latex/ctex/fontset/ctex-fontset-founder.def
%{_tl_texmf}/tex/latex/ctex/fontset/ctex-fontset-hanyi.def
%{_tl_texmf}/tex/latex/ctex/fontset/ctex-fontset-mac.def
%{_tl_texmf}/tex/latex/ctex/fontset/ctex-fontset-macnew.def
%{_tl_texmf}/tex/latex/ctex/fontset/ctex-fontset-macold.def
%{_tl_texmf}/tex/latex/ctex/fontset/ctex-fontset-ubuntu.def
%{_tl_texmf}/tex/latex/ctex/fontset/ctex-fontset-windows.def
%{_tl_texmf}/tex/latex/ctex/heading/ctex-heading-article.def
%{_tl_texmf}/tex/latex/ctex/heading/ctex-heading-beamer.def
%{_tl_texmf}/tex/latex/ctex/heading/ctex-heading-book.def
%{_tl_texmf}/tex/latex/ctex/heading/ctex-heading-report.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-chinese-article.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-chinese-beamer.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-chinese-book.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-chinese-report.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-chinese.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-plain-article.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-plain-beamer.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-plain-book.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-plain-report.def
%{_tl_texmf}/tex/latex/ctex/scheme/ctex-scheme-plain.def
%{_tl_texmf}/tex/latex/shtthesis/shtthesis.cls
%{_tl_texmf}/tex/latex/xebaposter/xebaposter.cls
%{_tl_texmf}/tex/luatex/ctex/ctex-zhconv-index.lua
%{_tl_texmf}/tex/luatex/ctex/ctex-zhconv.lua
%{_tl_texmf}/tex/xelatex/arabxetex/arabxetex.sty
%{_tl_texmf}/tex/xelatex/bidi-atbegshi/bidi-atbegshi.sty
%{_tl_texmf}/tex/xelatex/bidicontour/bidicontour.sty
%{_tl_texmf}/tex/xelatex/bidipagegrid/bidipagegrid.sty
%{_tl_texmf}/tex/xelatex/bidipresentation/bidiprescolors.cfg
%{_tl_texmf}/tex/xelatex/bidipresentation/bidipresentation.cls
%{_tl_texmf}/tex/xelatex/bidishadowtext/bidishadowtext.sty
%{_tl_texmf}/tex/xelatex/businesscard-qrcode/businesscard-qrcode.cls
%{_tl_texmf}/tex/xelatex/cqubeamer/cqubeamer.sty
%{_tl_texmf}/tex/xelatex/fixlatvian/fixlatvian.sty
%{_tl_texmf}/tex/xelatex/fontbook/fontbook.sty
%{_tl_texmf}/tex/xelatex/fontwrap/fontwrap.sty
%{_tl_texmf}/tex/xelatex/interchar/interchar.sty
%{_tl_texmf}/tex/xelatex/na-position/na-position.sty
%{_tl_texmf}/tex/xelatex/philokalia/philokalia.sty
%{_tl_texmf}/tex/xelatex/philokalia/tuplk.fd
%{_tl_texmf}/tex/xelatex/ptext/ptext.sty
%{_tl_texmf}/tex/xelatex/simple-resume-cv/simpleresumecv.cls
%{_tl_texmf}/tex/xelatex/simple-thesis-dissertation/simplethesisdissertation.cls
%{_tl_texmf}/tex/xelatex/tetragonos/tetragonos-database.def
%{_tl_texmf}/tex/xelatex/tetragonos/tetragonos.sty
%{_tl_texmf}/tex/xelatex/ucharclasses/ucharclasses.sty
%{_tl_texmf}/tex/xelatex/unicode-bidi/unicode-bidi.sty
%{_tl_texmf}/tex/xelatex/unisugar/unisugar.sty
%{_tl_texmf}/tex/xelatex/xechangebar/xechangebar.sty
%{_tl_texmf}/tex/xelatex/xecjk/xeCJK-listings.sty
%{_tl_texmf}/tex/xelatex/xecjk/xeCJK.cfg
%{_tl_texmf}/tex/xelatex/xecjk/xeCJK.sty
%{_tl_texmf}/tex/xelatex/xecjk/xeCJKfntef.sty
%{_tl_texmf}/tex/xelatex/xecjk/xunicode-addon.sty
%{_tl_texmf}/tex/xelatex/xecjk/xunicode-extra.def
%{_tl_texmf}/tex/xelatex/xecolor/xecolor.sty
%{_tl_texmf}/tex/xelatex/xecyr/xecyr.sty
%{_tl_texmf}/tex/xelatex/xeindex/xeindex.sty
%{_tl_texmf}/tex/xelatex/xespotcolor/xespotcolor.sty
%{_tl_texmf}/tex/xelatex/xetex-pstricks/pstricks.con
%{_tl_texmf}/tex/xelatex/xetexconfig/crop.cfg
%{_tl_texmf}/tex/xelatex/xevlna/xevlna.sty
%{_tl_texmf}/tex/xelatex/zbmath-review-template/zb-basics.sty
%{_tl_texmf}/tex/xelatex/zbmath-review-template/zbMATH.cls
%{_tl_texmf}/tex/xetex/font-change-xetex/font-change-xetex.tex
%{_tl_texmf}/tex/xetex/unimath-plain-xetex/unimath-plain-xetex.tex
%{_tl_texmf}/tex/xetex/xesearch/t-xesearch.tex
%{_tl_texmf}/tex/xetex/xesearch/xesearch.sty
%{_tl_texmf}/tex/xetex/xetex-pstricks/pstricks.con
%{_tl_texmf}/tex/xetex/xetexfontinfo/aat-info.tex
%{_tl_texmf}/tex/xetex/xetexfontinfo/opentype-info.tex
%{_tl_texmf}/tex/xetex/xetexko/hanja_hangul.tab
%{_tl_texmf}/tex/xetex/xetexko/hanjacom_hangul.tab
%{_tl_texmf}/tex/xetex/xetexko/hanjaexa_hangul.tab
%{_tl_texmf}/tex/xetex/xetexko/xetexko-font.sty
%{_tl_texmf}/tex/xetex/xetexko/xetexko-hanging.sty
%{_tl_texmf}/tex/xetex/xetexko/xetexko-josa.sty
%{_tl_texmf}/tex/xetex/xetexko/xetexko-space.sty
%{_tl_texmf}/tex/xetex/xetexko/xetexko-vertical.sty
%{_tl_texmf}/tex/xetex/xetexko/xetexko.sty

%changelog
* Sun Sep 27 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260927-1
- rolled to tlnet snapshot 20260927 (43 members)
