#!/usr/bin/env python3
"""Emit one spec per Arch-style texlive group (plus texlive-meta) from a
splitter partition.

Each group spec fetches ONLY its member tarballs from the immutable dated
tlnet-archive snapshot during %%build (the tlmgr wire layout serves every
package at <repo>/archive/<pkg>.tar.xz) — no install-tl, no scheme-full
download. Docs and sources are pruned after extraction (the tarballs bundle
them; the old staging install ran option_doc/option_src 0). Inter-group
Requires are version-pinned so every installed group stays on one snapshot.

Output is a pure function of (snapshot, archive_root, groups): identical
inputs produce byte-identical specs — the roll driver's idempotence and
the write-only-on-change guarantee both rest on that.
"""

from __future__ import annotations

import datetime
from pathlib import Path

CHANGELOG_IDENTITY = "halcyon-autoupdate <aahsnr041@proton.me>"

SPEC_HEADER = """\
# GENERATED by tools/texlive-splitter from tlnet-archive snapshot \
{snapshot} — do not
# edit by hand. Regenerated by the biweekly texlive roll \
(.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{{nil}}
%global __brp_mangle_shebangs %{{nil}}
%global _unpackaged_files_terminate_build 0

Name:           {name}
Version:        {snapshot}
Release:        1%{{?dist}}
Summary:        TeX Live {groupwords} collection — {shortdesc}
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url {archive_root}/{ys}/{ms}/{ds}/tlnet
%global _tl_texmf %{{_datadir}}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
"""

SPEC_BODY = """
%description
TeX Live {groupwords} collection ({shortdesc}) — the texmf-dist data tree
from tlnet snapshot {snapshot}, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
{members}
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \\
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \\
    "%{{_tl_archive_url}}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# upstream scripts carry pre-usrmerge shebangs (#!/bin/python3 and friends);
# the shebang mangler is disabled, so rpm would emit unresolvable file
# dependencies — normalize them to /usr/bin
find staging/texmf-dist -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {{}} + 2>/dev/null || true
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc
{lsr}
%install
mkdir -p "%{{buildroot}}%{{_tl_texmf}}"
cp -a staging/texmf-dist/. "%{{buildroot}}%{{_tl_texmf}}/"

%files
"""

LS_R_BLOCK = """\
# kpathsea filename database — install-tl generated this manifest in the
# old staging model; here it is derived from the fetched tree itself, in
# mktexlsr's directory-blocked format (block per directory, entries under
# it, every directory listed in its parent's block)
( printf '%%%% ls-R -- filename database for kpathsea.\\n%%%% Run mktexlsr to regenerate.\\n'
  cd staging/texmf-dist && find . -mindepth 1 | sed 's|^\\./||' | LC_ALL=C sort \\
  | awk -F/ '{ d="./"; for (i=1;i<NF;i++) d=d $i "/"; sub("/$", "", d); if (d!=p) { print d ":"; p=d } print $NF }'
) > staging/texmf-dist/ls-R
"""

META_SPEC = """\
# GENERATED by tools/texlive-splitter from tlnet-archive snapshot \
{snapshot} — do not
# edit by hand. The scheme-full catch-all: requires every group at this
# snapshot's version (docs excluded by design; binaries pair from Fedora).
%define debug_package %{{nil}}

Name:           texlive-meta
Version:        {snapshot}
Release:        1%{{?dist}}
Summary:        TeX Live scheme-full, without documentation
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

{requires}

%description
Metapackage installing every texlive-* group from tlnet snapshot
{snapshot} — Arch's texlive-meta shape, minus documentation. TeX engines
themselves come from Fedora's texlive packaging.

%build
cat > README <<'EOF'
texlive-meta — TeX Live scheme-full without documentation.

All texlive-* groups installed by this metapackage are pinned to tlnet
snapshot {snapshot}. Groups roll biweekly; dnf keeps them on one snapshot
via the version-pinned inter-group Requires.
EOF

%files
%doc README

%changelog
* {changelog_date} {identity} - {snapshot}-1
- metapackage for tlnet snapshot {snapshot} ({group_count} groups)
"""


def _changelog_date(snapshot: str) -> str:
    d = datetime.datetime.strptime(snapshot, "%Y%m%d")
    return d.strftime("%a %b %d %Y")


def render_group_spec(
    group: str, entry: dict, snapshot: str, archive_root: str
) -> str:
    name = group  # group already carries the "texlive-" prefix
    groupwords = group.removeprefix("texlive-")
    shortdesc = entry.get("shortdesc") or f"{groupwords} files"
    members = "\n".join(entry["members"])
    lsr = LS_R_BLOCK if group == "texlive-basic" else ""

    lines = [
        SPEC_HEADER.format(
            snapshot=snapshot,
            name=name,
            groupwords=groupwords,
            shortdesc=shortdesc,
            archive_root=archive_root,
            ys=snapshot[:4],
            ms=snapshot[4:6],
            ds=snapshot[6:],
        ),
    ]
    for dep in entry["depend"]:
        lines.append(f"Requires:       {dep} = %{{version}}\n")
    lines.append(
        SPEC_BODY.format(
            groupwords=groupwords,
            shortdesc=shortdesc,
            snapshot=snapshot,
            members=members,
            lsr=lsr,
        )
    )
    for rf in entry["runfiles"]:
        lines.append(f"%{{_tl_texmf}}/{rf.removeprefix('texmf-dist/')}\n")
    if group == "texlive-basic":
        lines.append("%{_tl_texmf}/ls-R\n")
    lines.append(
        f"\n%changelog\n"
        f"* {_changelog_date(snapshot)} {CHANGELOG_IDENTITY} - {snapshot}-1\n"
        f"- rolled to tlnet snapshot {snapshot} "
        f"({len(entry['members'])} members)\n"
    )
    return "".join(lines)


def render_meta_spec(groups: dict[str, dict], snapshot: str) -> str:
    requires = "\n".join(
        f"Requires:       {g} = %{{version}}" for g in sorted(groups)
    )
    return META_SPEC.format(
        snapshot=snapshot,
        requires=requires,
        changelog_date=_changelog_date(snapshot),
        identity=CHANGELOG_IDENTITY,
        group_count=len(groups),
    )


def emit_all(
    groups: dict[str, dict], snapshot: str, archive_root: str
) -> dict[str, str]:
    """Render every group + meta spec. Returns {name: spec_text} — writing
    is the caller's job (the roll driver writes only changed files)."""
    out: dict[str, str] = {}
    empty = []
    for group, entry in sorted(groups.items()):
        if not entry["runfiles"] and group != "texlive-basic":
            empty.append(group)
        out[group] = render_group_spec(group, entry, snapshot, archive_root)
    if empty:
        raise SystemExit(
            f"FATAL: groups with no runfiles at snapshot {snapshot}: "
            f"{', '.join(empty)} — would build empty RPMs; investigate the "
            "tlpdb before rolling."
        )
    out["texlive-meta"] = render_meta_spec(groups, snapshot)
    return out
