#!/usr/bin/env python3
"""Emit one spec per Arch-style texlive group (plus texlive-bin and
texlive-meta) from a splitter partition.

Each group spec fetches ONLY its member tarballs from the immutable dated
tlnet-archive snapshot during %%build (the tlmgr wire layout serves every
package at <repo>/archive/<pkg>.tar.xz) — no install-tl, no scheme-full
download. Docs and sources are pruned after extraction (the tarballs bundle
them; the old staging install ran option_doc/option_src 0). Inter-group
Requires are version-pinned so every installed group stays on one snapshot.

texlive-bin ships upstream's prebuilt x86_64-linux engine bundle from the
same snapshot under the SAME self-contained root, so kpathsea's
SELFAUTOPARENT resolution ties engines and data together with zero
interaction with Fedora's texlive packaging (different paths, different
package names).

Output is a pure function of (snapshot, archive_root, groups): identical
inputs produce byte-identical specs — the roll driver's idempotence and
the write-only-on-change guarantee both rest on that.
"""

from __future__ import annotations

import datetime
from pathlib import Path

CHANGELOG_IDENTITY = "halcyon-autoupdate <aahsnr041@proton.me>"

SPEC_HEADER = """\
# GENERATED by tools/texlive-splitter from tlnet-archive snapshot \
{snapshot} — do not
# edit by hand. Regenerated by the biweekly texlive roll \
(.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries — texlive-bin (upstream's
# x86_64-linux bundle) ships the engines under the same self-contained
# /usr/lib/texlive/<year> root, so nothing here interacts with Fedora's
# texlive packaging.
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{{nil}}
%global __brp_mangle_shebangs %{{nil}}
%global _unpackaged_files_terminate_build 0

Name:           {name}
Version:        {snapshot}
Release:        1%{{?dist}}
Summary:        TeX Live {groupwords} collection — {shortdesc}
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url {archive_root}/{ys}/{ms}/{ds}/tlnet
%global _tl_root %{{_prefix}}/lib/texlive/{ys}
%global _tl_texmf %{{_tl_root}}/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
"""

SPEC_BODY = """
%description
TeX Live {groupwords} collection ({shortdesc}) — the texmf-dist data tree
from tlnet snapshot {snapshot}, without documentation. Engines come from
texlive-bin (same snapshot) beside this tree under %{{_tl_root}}; install
texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
{members}
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \\
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \\
    "%{{_tl_archive_url}}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# upstream scripts carry pre-usrmerge shebangs (#!/bin/python3 and friends);
# the shebang mangler is disabled, so rpm would emit unresolvable file
# dependencies — normalize them to /usr/bin
find staging/texmf-dist -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {{}} + 2>/dev/null || true
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc
{lsr}
%install
mkdir -p "%{{buildroot}}%{{_tl_texmf}}"
cp -a staging/texmf-dist/. "%{{buildroot}}%{{_tl_texmf}}/"

%files
"""

LS_R_BLOCK = """\
# kpathsea filename database — install-tl generated this manifest in the
# old staging model; here it is derived from the fetched tree itself, in
# mktexlsr's directory-blocked format (block per directory, entries under
# it, every directory listed in its parent's block). The FIRST LINE must
# be mktexlsr's exact magic string: mktexlsr refuses to overwrite an ls-R
# whose header deviates ("no magic string, skipping") — the image's
# texlive-formats step regenerates the database after the transaction and
# would silently no-op otherwise.
( printf '%%%% ls-R -- filename database for kpathsea; do not change this line.\\n%%%% Run mktexlsr to regenerate.\\n'
  cd staging/texmf-dist && find . -mindepth 1 | sed 's|^\\./||' | LC_ALL=C sort \\
  | awk -F/ '{ d="./"; for (i=1;i<NF;i++) d=d $i "/"; sub("/$", "", d); if (d!=p) { print d ":"; p=d } print $NF }'
) > staging/texmf-dist/ls-R
"""

META_SPEC = """\
# GENERATED by tools/texlive-splitter from tlnet-archive snapshot \
{snapshot} — do not
# edit by hand. The scheme-full catch-all: requires every group plus the
# engine package at this snapshot's version (docs excluded by design;
# engines ship in texlive-bin).
%define debug_package %{{nil}}

Name:           texlive-meta
Version:        {snapshot}
Release:        1%{{?dist}}
Summary:        TeX Live scheme-full, without documentation
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

{requires}

%description
Metapackage installing every texlive-* group from tlnet snapshot
{snapshot} — Arch's texlive-meta shape, minus documentation. TeX engines
ship in texlive-bin from the same snapshot.

%build
cat > README <<'EOF'
texlive-meta — TeX Live scheme-full without documentation.

All texlive-* groups installed by this metapackage are pinned to tlnet
snapshot {snapshot}. Groups roll biweekly; dnf keeps them on one snapshot
via the version-pinned inter-group Requires.
EOF

%files
%doc README

%changelog
* {changelog_date} {identity} - {snapshot}-1
- metapackage for tlnet snapshot {snapshot} ({group_count} groups)
"""

BIN_SPEC = """\
# GENERATED by tools/texlive-splitter from tlnet-archive snapshot \
{snapshot} — do not
# edit by hand. Regenerated by the biweekly texlive roll \
(.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py). The ENGINE half
# of the split: upstream's prebuilt x86_64-linux binary bundle from the
# same dated snapshot. kpathsea resolves the tree relative to the binary
# location (TEXMFROOT = $SELFAUTOPARENT), so the bundle works unmodified
# under the self-contained /usr/lib/texlive/<year> root and nothing here
# touches Fedora's texlive packaging (different paths, different names).
# The build fetches the bundle + the repository tlpdb from the immutable
# dated snapshot during %%build (network is on in Copr).
%define debug_package %{{nil}}
%global __brp_mangle_shebangs %{{nil}}
%global _unpackaged_files_terminate_build 0

Name:           texlive-bin
Version:        {snapshot}
Release:        1%{{?dist}}
Summary:        TeX Live engine binaries (upstream x86_64-linux bundle)
BuildArch:      x86_64
ExclusiveArch:  x86_64
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url {archive_root}/{ys}/{ms}/{ds}/tlnet
%global _tl_root %{{_prefix}}/lib/texlive/{ys}

# the binaries are useless without the core data tree — the only coupling
# the engine package carries; every other group is pulled by the consumer
Requires:       texlive-basic = %{{version}}

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz

%description
TeX Live engine binaries from tlnet snapshot {snapshot} (the upstream
x86_64-linux bundle) plus the repository tlpdb tlmgr needs, installed
under the self-contained root %{{_tl_root}}. The group packages ship the
texmf-dist data tree beside it; kpathsea ties them together through the
binary location alone. Requires texlive-basic (the core data).

%build
mkdir -p raw
cat > members.txt <<'EOF'
{members}
EOF
# the wire stores platform binaries as per-package tarballs
# (<pkg>.x86_64-linux.tar.xz — what install-tl fetches one by one)
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \\
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \\
    "%{{_tl_archive_url}}/archive/PKG.tar.xz"
# most tarballs carry bin/x86_64-linux pre-rooted (non-reloc shape); a
# root-level file dump is normalized into the same staging tree
mkdir -p staging/bin/x86_64-linux
for t in raw/*.tar.xz; do
    d="raw/$(basename "$t" .tar.xz)"
    mkdir -p "$d"
    tar -xJf "$t" -C "$d"
    if [ -d "$d/bin/x86_64-linux" ]; then
        cp -a "$d/bin/x86_64-linux/." staging/bin/x86_64-linux/
    else
        find "$d" -mindepth 1 -maxdepth 1 -type f \\
            -exec cp -a -t staging/bin/x86_64-linux/ {{}} +
    fi
done
# upstream scripts/wrappers carry pre-usrmerge shebangs; normalize like the
# data groups do so rpm emits resolvable file dependencies
find staging/bin -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {{}} + 2>/dev/null || true
# the TeXLive perl modules (TLUtils.pm & co.) live in the texlive.infra
# DATA package's tlpkg/ — the platform tarballs only carry bin/. Without
# them the fmtutil/updmap/tlmgr wrappers abort on `use TeXLive::TLUtils`.
wget -q --retry-connrefused --waitretry=5 --tries=5 \\
    -O raw/texlive.infra.tar.xz \\
    "%{{_tl_archive_url}}/archive/texlive.infra.tar.xz"
mkdir -p raw/texlive.infra staging/tlpkg
tar -xJf raw/texlive.infra.tar.xz -C raw/texlive.infra
if [ -d raw/texlive.infra/tlpkg ]; then
    cp -a raw/texlive.infra/tlpkg/. staging/tlpkg/
fi
# the repository tlpdb tlmgr needs
wget -q --retry-connrefused --waitretry=5 --tries=5 \\
    -O raw/texlive.tlpdb.xz \\
    "%{{_tl_archive_url}}/tlpkg/texlive.tlpdb.xz"
xz -dc raw/texlive.tlpdb.xz > staging/tlpkg/texlive.tlpdb
# pin tlmgr to this snapshot's repository (the archive URL is immutable)
mkdir -p staging/texmf-config/tlmgr
printf 'repository = %s\\nverify-repo = none\\n' "%{{_tl_archive_url}}" \\
    > staging/texmf-config/tlmgr/config

%install
mkdir -p "%{{buildroot}}%{{_tl_root}}/bin" \\
         "%{{buildroot}}%{{_tl_root}}/tlpkg" \\
         "%{{buildroot}}%{{_tl_root}}/texmf-config" \\
         "%{{buildroot}}%{{_sysconfdir}}/profile.d"
cp -a staging/bin/x86_64-linux "%{{buildroot}}%{{_tl_root}}/bin/"
# the WHOLE tlpkg ships: not just the tlpdb — fmtutil/updmap/tlmgr abort at
# startup on `use TeXLive::TLUtils` without the TeXLive/*.pm modules, and a
# tlpkg holding only the tlpdb is exactly how the image lost every format
# the day the /usr/bin engine links stopped pulling Fedora's
# texlive-texlive.infra (the accidental module provider). The dir is +920 K.
cp -a staging/tlpkg/. "%{{buildroot}}%{{_tl_root}}/tlpkg/"
cp -a staging/texmf-config/tlmgr "%{{buildroot}}%{{_tl_root}}/texmf-config/"
# expose the linkable engines in /usr/bin: the data groups' scripts carry
# engine shebangs, so rpm auto-requires /usr/bin/<engine>, and the consumer
# drop-in's priority=1 shadows the Fedora packages that would otherwise
# provide them — without this texlive-pictures cannot satisfy its
# /usr/bin/luatex dependency from this project at all. The list is by name,
# not by glob: every other binary in the engine dir is owned by a Fedora
# package this project does not build (texlive-kpathsea, texlive-pdftex,
# psutils, asymptote, ...), and shipping it here would file-conflict for
# anyone who has that package installed. lualatex is the single deliberate
# exception — Fedora's texlive-luahbtex owns it on updates — kept because
# this project's texlive-luatex is data-only and can never provide it.
_TL_BINDIR="biber-ms cjk-gs-integrate context.lua dvilualatex dvilualatex-dev dviluatex dvitomp latex luacsplain luametatex lualatex luatex make-paper-tarball mfplain mpost mtxrun.lua pdflatex r-mpost texchanges-merge texlua texluac tlcockpit tlshell xdvipdfmx xelatex xelatex-dev xelatex-unsafe xetex xetex-unsafe xindy.run"
mkdir -p "%{{buildroot}}%{{_bindir}}"
: > engine-links.list
for _tl_exe in $_TL_BINDIR; do
    ln -s "%{{_tl_root}}/bin/x86_64-linux/$_tl_exe" "%{{buildroot}}%{{_bindir}}/$_tl_exe"
    printf '/usr/bin/%s\\n' "$_tl_exe" >> engine-links.list
done
# PATH hook: prepend the engine dir of the newest installed year; kpathsea
# needs nothing else here (SELFAUTOPARENT does the rest)
cat > "%{{buildroot}}%{{_sysconfdir}}/profile.d/texlive.sh" <<'EOF'
#!/bin/sh
# TeX Live (rolling, packaged from tlnet snapshots) — upstream engines
# under /usr/lib/texlive/<year>; kpathsea resolves the tree relative to
# the binary (SELFAUTOPARENT), so only PATH is wired here.
for _tl_bin in /usr/lib/texlive/*/bin/x86_64-linux; do
    [ -d "$_tl_bin" ] || continue
    case ":$PATH:" in
        *":$_tl_bin:"*) ;;
        *) PATH="$_tl_bin:$PATH" ;;
    esac
done
export PATH
unset _tl_bin
EOF
chmod 0755 "%{{buildroot}}%{{_sysconfdir}}/profile.d/texlive.sh"

%files -f engine-links.list
%{{_tl_root}}/bin/
%{{_tl_root}}/tlpkg/
%{{_tl_root}}/texmf-config/
%{{_sysconfdir}}/profile.d/texlive.sh

%changelog
* {changelog_date} {identity} - {snapshot}-1
- engine bundle for tlnet snapshot {snapshot}
"""


def _changelog_date(snapshot: str) -> str:
    d = datetime.datetime.strptime(snapshot, "%Y%m%d")
    return d.strftime("%a %b %d %Y")


def render_group_spec(
    group: str, entry: dict, snapshot: str, archive_root: str
) -> str:
    name = group  # group already carries the "texlive-" prefix
    groupwords = group.removeprefix("texlive-")
    shortdesc = entry.get("shortdesc") or f"{groupwords} files"
    members = "\n".join(entry["members"])
    lsr = LS_R_BLOCK if group == "texlive-basic" else ""

    lines = [
        SPEC_HEADER.format(
            snapshot=snapshot,
            name=name,
            groupwords=groupwords,
            shortdesc=shortdesc,
            archive_root=archive_root,
            ys=snapshot[:4],
            ms=snapshot[4:6],
            ds=snapshot[6:],
        ),
    ]
    for dep in entry["depend"]:
        lines.append(f"Requires:       {dep} = %{{version}}\n")
    lines.append(
        SPEC_BODY.format(
            groupwords=groupwords,
            shortdesc=shortdesc,
            snapshot=snapshot,
            members=members,
            lsr=lsr,
        )
    )
    for rf in entry["runfiles"]:
        lines.append(f"%{{_tl_texmf}}/{rf.removeprefix('texmf-dist/')}\n")
    if group == "texlive-basic":
        lines.append("%{_tl_texmf}/ls-R\n")
    lines.append(
        f"\n%changelog\n"
        f"* {_changelog_date(snapshot)} {CHANGELOG_IDENTITY} - {snapshot}-1\n"
        f"- rolled to tlnet snapshot {snapshot} "
        f"({len(entry['members'])} members)\n"
    )
    return "".join(lines)


def render_meta_spec(groups: dict[str, dict], snapshot: str) -> str:
    requires = "\n".join(
        f"Requires:       {g} = %{{version}}" for g in sorted(groups)
    )
    # the engine package rides along at the same snapshot — meta is the
    # "everything" entry point, engines included
    requires += "\nRequires:       texlive-bin = %{version}"
    return META_SPEC.format(
        snapshot=snapshot,
        requires=requires,
        changelog_date=_changelog_date(snapshot),
        identity=CHANGELOG_IDENTITY,
        group_count=len(groups),
    )


def render_bin_spec(
    members: list[str], snapshot: str, archive_root: str
) -> str:
    return BIN_SPEC.format(
        members="\n".join(members),
        snapshot=snapshot,
        archive_root=archive_root,
        ys=snapshot[:4],
        ms=snapshot[4:6],
        ds=snapshot[6:],
        changelog_date=_changelog_date(snapshot),
        identity=CHANGELOG_IDENTITY,
    )


def emit_all(
    groups: dict[str, dict],
    snapshot: str,
    archive_root: str,
    platform_members: list[str] | None = None,
) -> dict[str, str]:
    """Render every group + texlive-bin + meta spec. Returns
    {name: spec_text} — writing is the caller's job (the roll driver
    writes only changed files). platform_members are the tlpdb's
    <pkg>.x86_64-linux binary-package names fetched by texlive-bin."""
    out: dict[str, str] = {}
    empty = []
    for group, entry in sorted(groups.items()):
        if not entry["runfiles"] and group != "texlive-basic":
            empty.append(group)
        out[group] = render_group_spec(group, entry, snapshot, archive_root)
    if empty:
        raise SystemExit(
            f"FATAL: groups with no runfiles at snapshot {snapshot}: "
            f"{', '.join(empty)} — would build empty RPMs; investigate the "
            "tlpdb before rolling."
        )
    out["texlive-bin"] = render_bin_spec(
        platform_members or [], snapshot, archive_root
    )
    out["texlive-meta"] = render_meta_spec(groups, snapshot)
    return out
