# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260927 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-metapost
Version:        20260927
Release:        1%{?dist}
Summary:        TeX Live metapost collection — MetaPost and Metafont packages
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/27/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-basic = %{version}

%description
TeX Live metapost collection (MetaPost and Metafont packages) — the texmf-dist data tree
from tlnet snapshot 20260927, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
automata
bbcard
blockdraw_mp
bpolynomial
cmarrows
drv
dviincl
emp
epsincl
expressg
exteps
featpost
feynmf
feynmp-auto
fiziko
garrigues
gmp
hatching
hershey-mp
huffman
latexmp
mcf2graph
metago
metaobj
metaplot
metapost
metapost-colorbrewer
metauml
mfpic
mfpic4ode
minim-hatching
mp-gears
mp-geom2d
mp-neuralnetwork
mp3d
mparrows
mpattern
mpchess
mpcolornames
mpgraphics
mpkiviat
mptrees
piechartmp
repere
roex
roundrect
shapes
slideshow
splines
suanpan
textpath
threeddice
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# upstream scripts carry pre-usrmerge shebangs (#!/bin/python3 and friends);
# the shebang mangler is disabled, so rpm would emit unresolvable file
# dependencies — normalize them to /usr/bin
find staging/texmf-dist -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {} + 2>/dev/null || true
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/fonts/afm/metapost/freeeuro.afm
%{_tl_texmf}/fonts/afm/metapost/psyrgo.afm
%{_tl_texmf}/fonts/afm/metapost/zpzdr-reversed.afm
%{_tl_texmf}/fonts/enc/dvips/metapost/groff.enc
%{_tl_texmf}/fonts/map/dvips/metapost/troff-updmap.map
%{_tl_texmf}/fonts/map/dvips/metapost/troff.map
%{_tl_texmf}/fonts/tfm/metapost/freeeuro.tfm
%{_tl_texmf}/fonts/tfm/metapost/pagd8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pagdo8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pagk8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pagko8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pbkd8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pbkdi8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pbkl8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pbkli8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pcrb8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pcrbo8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pcrr8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pcrro8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/phvb8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/phvb8gn.tfm
%{_tl_texmf}/fonts/tfm/metapost/phvbo8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/phvbo8gn.tfm
%{_tl_texmf}/fonts/tfm/metapost/phvr8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/phvr8gn.tfm
%{_tl_texmf}/fonts/tfm/metapost/phvro8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/phvro8gn.tfm
%{_tl_texmf}/fonts/tfm/metapost/pncb8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pncbi8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pncr8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pncri8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pplb8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pplbi8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pplr8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pplri8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/psyrgo.tfm
%{_tl_texmf}/fonts/tfm/metapost/ptmb8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/ptmbi8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/ptmr8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/ptmri8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/pzcmi8g.tfm
%{_tl_texmf}/fonts/tfm/metapost/zpzdr-reversed.tfm
%{_tl_texmf}/fonts/truetype/public/mpchess/mpchessfont.ttf
%{_tl_texmf}/fonts/type1/metapost/freeeuro.pfa
%{_tl_texmf}/metafont/feynmf/feynmf.mf
%{_tl_texmf}/metafont/mfpic/grafbase.mf
%{_tl_texmf}/metafont/roex/roex.mf
%{_tl_texmf}/metapost/automata/automata.mp
%{_tl_texmf}/metapost/base/TEX.mp
%{_tl_texmf}/metapost/base/boxes.mp
%{_tl_texmf}/metapost/base/format.mp
%{_tl_texmf}/metapost/base/graph.mp
%{_tl_texmf}/metapost/base/marith.mp
%{_tl_texmf}/metapost/base/mfplain.mp
%{_tl_texmf}/metapost/base/mpost.mp
%{_tl_texmf}/metapost/base/plain.mp
%{_tl_texmf}/metapost/base/pmpost.mp
%{_tl_texmf}/metapost/base/rboxes.mp
%{_tl_texmf}/metapost/base/sarith.mp
%{_tl_texmf}/metapost/base/string.mp
%{_tl_texmf}/metapost/base/texnum.mp
%{_tl_texmf}/metapost/base/troffnum.mp
%{_tl_texmf}/metapost/base/upmpost.mp
%{_tl_texmf}/metapost/bbcard/bbcard.mp
%{_tl_texmf}/metapost/bbcard/breakwidth.mp
%{_tl_texmf}/metapost/bbcard/calendar.mp
%{_tl_texmf}/metapost/bbcard/scorecard.mp
%{_tl_texmf}/metapost/blockdraw_mp/blockdraw.mp
%{_tl_texmf}/metapost/blockdraw_mp/bonddemo.mp
%{_tl_texmf}/metapost/blockdraw_mp/bondgraph.mp
%{_tl_texmf}/metapost/blockdraw_mp/cascadedemo.mp
%{_tl_texmf}/metapost/blockdraw_mp/docblockprefs.mp
%{_tl_texmf}/metapost/blockdraw_mp/shiftoff.mp
%{_tl_texmf}/metapost/bpolynomial/bpolynomial.mp
%{_tl_texmf}/metapost/cmarrows/cmarrows.mp
%{_tl_texmf}/metapost/cmarrows/rgbx0009.mp
%{_tl_texmf}/metapost/cmarrows/rgbx0016.mp
%{_tl_texmf}/metapost/cmarrows/rgbx0020.mp
%{_tl_texmf}/metapost/cmarrows/rgbx0025.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0008.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0010.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0011.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0012.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0013.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0014.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0015.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0017.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0018.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0019.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0021.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0022.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0023.mp
%{_tl_texmf}/metapost/cmarrows/sgbx0024.mp
%{_tl_texmf}/metapost/cmarrows/tgbx0000.mp
%{_tl_texmf}/metapost/cmarrows/tgbx0001.mp
%{_tl_texmf}/metapost/cmarrows/tgbx0002.mp
%{_tl_texmf}/metapost/cmarrows/tgbx0003.mp
%{_tl_texmf}/metapost/cmarrows/tgbx0004.mp
%{_tl_texmf}/metapost/cmarrows/tgbx0005.mp
%{_tl_texmf}/metapost/cmarrows/tgbx0006.mp
%{_tl_texmf}/metapost/cmarrows/tgbx0007.mp
%{_tl_texmf}/metapost/cmarrows/tgbx0027.mp
%{_tl_texmf}/metapost/config/mfplain.ini
%{_tl_texmf}/metapost/drv/drv.mp
%{_tl_texmf}/metapost/dviincl/fix_brks.mp
%{_tl_texmf}/metapost/dviincl/fix_page.mp
%{_tl_texmf}/metapost/epsincl/epsincl.mp
%{_tl_texmf}/metapost/expressg/aam.mp
%{_tl_texmf}/metapost/expressg/expeg.mp
%{_tl_texmf}/metapost/expressg/expressg.mp
%{_tl_texmf}/metapost/exteps/exteps.mp
%{_tl_texmf}/metapost/featpost/featpost.mp
%{_tl_texmf}/metapost/featpost/featpost3Dplus2D.mp
%{_tl_texmf}/metapost/feynmf/feynmp.mp
%{_tl_texmf}/metapost/feynmf/manpics.mp
%{_tl_texmf}/metapost/fiziko/fiziko.mp
%{_tl_texmf}/metapost/garrigues/garrigues.mp
%{_tl_texmf}/metapost/hatching/hatching.mp
%{_tl_texmf}/metapost/hershey-mp/hershey.mp
%{_tl_texmf}/metapost/huffman/huffman.mp
%{_tl_texmf}/metapost/latexmp/latexmp.mp
%{_tl_texmf}/metapost/mcf2graph/main_lib.mcf
%{_tl_texmf}/metapost/mcf2graph/mcf2graph.mp
%{_tl_texmf}/metapost/metago/metago.mp
%{_tl_texmf}/metapost/metaobj/connections.mp
%{_tl_texmf}/metapost/metaobj/metaobj.mp
%{_tl_texmf}/metapost/metaobj/mobjstandard.mp
%{_tl_texmf}/metapost/metaobj/proofex.mp
%{_tl_texmf}/metapost/metaobj/pstricksex1.mp
%{_tl_texmf}/metapost/metaobj/pstricksex2.mp
%{_tl_texmf}/metapost/metaobj/pstricksex3.mp
%{_tl_texmf}/metapost/metaobj/pstricksex4.mp
%{_tl_texmf}/metapost/metaplot/axes.mp
%{_tl_texmf}/metapost/metaplot/metaplot.mp
%{_tl_texmf}/metapost/metapost-colorbrewer/colorbrewer-cmyk.mp
%{_tl_texmf}/metapost/metapost-colorbrewer/colorbrewer-rgb.mp
%{_tl_texmf}/metapost/metauml/metauml.mp
%{_tl_texmf}/metapost/metauml/metauml_activity.mp
%{_tl_texmf}/metapost/metauml/metauml_base.mp
%{_tl_texmf}/metapost/metauml/metauml_behavioral_common.mp
%{_tl_texmf}/metapost/metauml/metauml_class.mp
%{_tl_texmf}/metapost/metauml/metauml_class_assoc.mp
%{_tl_texmf}/metapost/metauml/metauml_class_relations.mp
%{_tl_texmf}/metapost/metauml/metauml_component.mp
%{_tl_texmf}/metapost/metauml/metauml_component_relations.mp
%{_tl_texmf}/metapost/metauml/metauml_defaults.mp
%{_tl_texmf}/metapost/metauml/metauml_instance.mp
%{_tl_texmf}/metapost/metauml/metauml_links.mp
%{_tl_texmf}/metapost/metauml/metauml_note.mp
%{_tl_texmf}/metapost/metauml/metauml_package.mp
%{_tl_texmf}/metapost/metauml/metauml_package_relations.mp
%{_tl_texmf}/metapost/metauml/metauml_paths.mp
%{_tl_texmf}/metapost/metauml/metauml_skin_simple.mp
%{_tl_texmf}/metapost/metauml/metauml_state.mp
%{_tl_texmf}/metapost/metauml/metauml_stereotype.mp
%{_tl_texmf}/metapost/metauml/metauml_templates.mp
%{_tl_texmf}/metapost/metauml/metauml_usecase.mp
%{_tl_texmf}/metapost/metauml/metauml_usecase_clipart.mp
%{_tl_texmf}/metapost/metauml/util_commons.mp
%{_tl_texmf}/metapost/metauml/util_group.mp
%{_tl_texmf}/metapost/metauml/util_infrastructure.mp
%{_tl_texmf}/metapost/metauml/util_log.mp
%{_tl_texmf}/metapost/metauml/util_margins.mp
%{_tl_texmf}/metapost/metauml/util_object.mp
%{_tl_texmf}/metapost/metauml/util_picture.mp
%{_tl_texmf}/metapost/metauml/util_picture_stack.mp
%{_tl_texmf}/metapost/metauml/util_positioning.mp
%{_tl_texmf}/metapost/metauml/util_shade.mp
%{_tl_texmf}/metapost/mfpic/dvipsnam.mp
%{_tl_texmf}/metapost/mfpic/grafbase.mp
%{_tl_texmf}/metapost/minim-hatching/minim-hatching.mp
%{_tl_texmf}/metapost/misc/null.mp
%{_tl_texmf}/metapost/mp-gears/gears.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d-arc.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d-c2d.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d-fct.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d-lbl.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d-main.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d-plt.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d-rep.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d-svgnames.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d-tra.mp
%{_tl_texmf}/metapost/mp-geom2d/geom2d.mp
%{_tl_texmf}/metapost/mp-neuralnetwork/mp-neuralnetwork-metaobj-patch.mp
%{_tl_texmf}/metapost/mp-neuralnetwork/mp-neuralnetwork.mp
%{_tl_texmf}/metapost/mp3d/3d.mp
%{_tl_texmf}/metapost/mp3d/3danim.mp
%{_tl_texmf}/metapost/mp3d/3dgeom.mp
%{_tl_texmf}/metapost/mp3d/3dpoly.mp
%{_tl_texmf}/metapost/mp3d/3dutil.mp
%{_tl_texmf}/metapost/mp3d/animpoly.mp
%{_tl_texmf}/metapost/mparrows/mparrows.mp
%{_tl_texmf}/metapost/mpattern/mpattern.mp
%{_tl_texmf}/metapost/mpchess/mpchess-cburnett.mp
%{_tl_texmf}/metapost/mpchess/mpchess-chessboard.mp
%{_tl_texmf}/metapost/mpchess/mpchess-fen.mp
%{_tl_texmf}/metapost/mpchess/mpchess-pgn.mp
%{_tl_texmf}/metapost/mpchess/mpchess-pieces.mp
%{_tl_texmf}/metapost/mpchess/mpchess-skak.mp
%{_tl_texmf}/metapost/mpchess/mpchess.mp
%{_tl_texmf}/metapost/mpcolornames/mpcolornames-spec-dvipsnam-def.mp
%{_tl_texmf}/metapost/mpcolornames/mpcolornames-spec-plain-mp.mp
%{_tl_texmf}/metapost/mpcolornames/mpcolornames-spec-svgnam-def.mp
%{_tl_texmf}/metapost/mpcolornames/mpcolornames-spec-x11nam-def.mp
%{_tl_texmf}/metapost/mpcolornames/mpcolornames-spec-xcolor-sty.mp
%{_tl_texmf}/metapost/mpcolornames/mpcolornames.mp
%{_tl_texmf}/metapost/mpkiviat/mpkiviat.mp
%{_tl_texmf}/metapost/mptrees/mptrees.mp
%{_tl_texmf}/metapost/piechartmp/piechartmp.mp
%{_tl_texmf}/metapost/repere/repere.mp
%{_tl_texmf}/metapost/roundrect/roundrect.mp
%{_tl_texmf}/metapost/shapes/shapes.mp
%{_tl_texmf}/metapost/slideshow/pathalong.mp
%{_tl_texmf}/metapost/slideshow/slideshow.mp
%{_tl_texmf}/metapost/slideshow/sshowex.mp
%{_tl_texmf}/metapost/slideshow/sshowex2.mp
%{_tl_texmf}/metapost/slideshow/sshowex3.mp
%{_tl_texmf}/metapost/slideshow/sshowintro.mp
%{_tl_texmf}/metapost/splines/splines.mp
%{_tl_texmf}/metapost/splines/testsplines.mp
%{_tl_texmf}/metapost/suanpan/abacus.mp
%{_tl_texmf}/metapost/suanpan/suanpan.mp
%{_tl_texmf}/metapost/support/charlib/12
%{_tl_texmf}/metapost/support/charlib/14
%{_tl_texmf}/metapost/support/charlib/34
%{_tl_texmf}/metapost/support/charlib/Ao
%{_tl_texmf}/metapost/support/charlib/Fi
%{_tl_texmf}/metapost/support/charlib/Fl
%{_tl_texmf}/metapost/support/charlib/L1
%{_tl_texmf}/metapost/support/charlib/LH
%{_tl_texmf}/metapost/support/charlib/Lb
%{_tl_texmf}/metapost/support/charlib/Sl
%{_tl_texmf}/metapost/support/charlib/ao.x
%{_tl_texmf}/metapost/support/charlib/bx
%{_tl_texmf}/metapost/support/charlib/ci
%{_tl_texmf}/metapost/support/charlib/ff
%{_tl_texmf}/metapost/support/charlib/lh.x
%{_tl_texmf}/metapost/support/charlib/ob
%{_tl_texmf}/metapost/support/charlib/rh
%{_tl_texmf}/metapost/support/charlib/sq
%{_tl_texmf}/metapost/support/charlib/twiddle
%{_tl_texmf}/metapost/support/trchars.adj
%{_tl_texmf}/metapost/support/trfonts.map
%{_tl_texmf}/metapost/textpath/textpath.mp
%{_tl_texmf}/metapost/threeddice/threeddice.mp
%{_tl_texmf}/tex/generic/metapost/mproof.tex
%{_tl_texmf}/tex/generic/metapost/mpsproof.tex
%{_tl_texmf}/tex/generic/mfpic/mfpic.sty
%{_tl_texmf}/tex/generic/mfpic/mfpic.tex
%{_tl_texmf}/tex/generic/mfpic/mfpicdef.tex
%{_tl_texmf}/tex/latex/emp/emp.sty
%{_tl_texmf}/tex/latex/feynmf/feynmf.sty
%{_tl_texmf}/tex/latex/feynmf/feynmp.sty
%{_tl_texmf}/tex/latex/feynmp-auto/feynmp-auto.sty
%{_tl_texmf}/tex/latex/gmp/gmp.sty
%{_tl_texmf}/tex/latex/mfpic4ode/mfpic4ode.sty
%{_tl_texmf}/tex/latex/mfpic4ode/mfpic4ode.tex
%{_tl_texmf}/tex/latex/mpgraphics/mpgraphics.sty
%{_tl_texmf}/tex/latex/textpath/textpathmp.sty

%changelog
* Sun Sep 27 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260927-1
- rolled to tlnet snapshot 20260927 (52 members)
